---
name: Codespell

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  codespell:
    name: Check for spelling errors
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install asdf & tools
        uses: asdf-vm/actions/install@v3

      - name: Add asdf to PATH
        run: echo "~/.asdf/shims" >> $GITHUB_PATH

      - name: Codespell
        run: |
          yarn global add cspell@latest
          make spellcheck-code
