name: Docs

on: [push]

jobs:
  spelling:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install asdf & tools
        uses: asdf-vm/actions/install@v3

      - name: Add asdf to PATH
        run: echo "~/.asdf/shims" >> $GITHUB_PATH

      - name: Codespell - Docs
        run: |
          yarn global add cspell@latest
          make spellcheck-docs

  build:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}

    steps:
      - uses: actions/checkout@v4

      - name: Install asdf & tools
        uses: asdf-vm/actions/install@v3

      - name: Add asdf to PATH
        run: echo "~/.asdf/shims" >> $GITHUB_PATH

      - name: Install corepack, nodejs, yarn
        run: |
          corepack enable
          asdf reshim nodejs
          yarn install
        working-directory: docs
      - run: yarn run build
        working-directory: docs
      - uses: actions/upload-artifact@v3
        with:
          path: docs/build/

  deploy:
    runs-on: ubuntu-latest
    needs: build

    if: github.ref == 'refs/heads/main'

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write # to deploy to Pages
      id-token: write # to verify the deployment originates from an appropriate source

    # Deploy to the environment
    environment:
      name: Github Pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - id: deployment
        uses: actions/deploy-pages@v2
