name: Lints

on:
  pull_request:
  push:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - run: echo "GO_VER=$(cat .tool-versions | grep go | cut -d' ' -f2 )" >> $GITHUB_ENV
      - run: echo "NODE_VER=$(cat .tool-versions | grep nodejs | cut -d' ' -f2)" >> $GITHUB_ENV

      - uses: actions/setup-go@v4
        with:
          go-version: "${{ env.GO_VER }}"
      - run: go mod tidy
      - run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.55.2
      - uses: pre-commit/action@v3.0.0
